### ISSUE TITLE
`saw-rustc --version` panics (but `crux-rustc --version` doesn't)

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/mir-json#50]
While `crux-rustc --version` works as you would expect:

```
$ crux-rustc --version
normal build - ["rustc", "--version", "--target", "x86_64-unknown-linux-gnu", "--cfg", "crux"]
rustc 1.69.0-nightly (5e37043d6 2023-01-22)
```

`saw-rustc --version`, on the other hand, will panic:

```
$ RUST_BACKTRACE=1 saw-rustc --version
test build - extract output path - ["rustc", "--version", "--test", "--target", "x86_64-unknown-linux-gnu", "--cfg", "crux"]
rustc 1.69.0-nightly (5e37043d6 2023-01-22)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/bin/mir-json-rustc-wrapper.rs:86:27
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/5e37043d63bfe2f3be8fa5a05b07d6c0dad5775d/library/core/src/panicking.rs:114:5
   3: mir_json_rustc_wrapper_real::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The backtrace points to this line as the culprit:

https://github.com/GaloisInc/mir-json/blob/3b538589852282a752e517b69fc61b627cd6d4bd/src/bin/mir-json-rustc-wrapper.rs#L86

I'm somewhat surprised by this, given how similar the two commands are. At first glance, one possible explanation is that `saw-rustc` calls `rustc` with `--test`, but `crux-rustc` does not.

**Comment by RyanGlScott** [comment]
See also https://github.com/GaloisInc/mir-json/issues/77. I suspect that we may need to reimplement some or all of the logic that powers the `--version` option in order to fix this.

**Comment by RyanGlScott** [comment]
Excellent sleuthing!

A follow-up thought: would this be easier to handle if `saw-rustc` _didn't_ use `--test`? The fact that `saw-rustc` uses `--test` under the hood is not really intentional, but more of an implementation-related coincidence. That is, when I first implemented `saw-rustc`, it was convenient to mirror the implementation of `crux-rustc`, which also happens to use `--test`. Part of me wonders removing the use of `--test` would fix bugs like this one (or https://github.com/GaloisInc/mir-json/issues/84, which is in related territory) automatically.
